### ISSUE TITLE
Thoughts on allowing elisp functions as compilers?

### ISSUE THREAD

**Issue by duckwork** [flajann2/schlau-compile#1]
I have a workflow that can be thought of as compilation, so I want to use `compile`'s functionality, but it's all in elisp --- namely, a specific `org-export` workflow that's the same every time I run it.

I've added a function to my own init.el to allow this, but it might be a good idea to include in this package.

**Comment by flajann2** [comment]
I would be happy to accept your pull request!

**Comment by duckwork** [comment]
Oh, nevermind -- I should've read the source, they're already possible!

**Comment by flajann2** [comment]
Cool!
